/-
# Residue Avoidance ↔ Shifted Multiples Bridge

This file connects the residue-avoidance vocabulary of Erdős problem `#25`
(see `Erdos.ResidueAvoidingDensity.Statement`) with the shared
`MultiplesOf`/`IsThick` vocabulary in `Erdos.Common.ThickSequences`
(originally mined from Google DeepMind's Erdős `#26` formalization;
Apache 2.0).

The forbidden set of the `i`-th constraint is

  `forbiddenSet S i = { n : ℕ | nᵢ ≤ n ∧ n ≡ aᵢ (mod nᵢ) }`

and the avoided set is

  `avoidedSet S = ℕ \ ⋃ i, forbiddenSet S i`.

In the special case `aᵢ = 0` we have `forbiddenSet S i = MultiplesOf (singleton nᵢ) ∩ [nᵢ, ∞)`,
so the avoided set is the complement of a union of shifted multiples,
which is the bridge object studied in `Erdos.Common.ThickSequences`.

Reference: https://www.erdosproblems.com/25
-/
import Erdos.Common.ThickSequences
import Erdos.ResidueAvoidingDensity.Elementary

set_option linter.style.header false

namespace ResidueAvoidingDensity
namespace ResidueSystem

open Erdos.Common

/-- The `i`-th *forbidden set*: integers at or above the threshold `modulus i`
that hit the residue class `aᵢ mod nᵢ`. By construction, the avoided set
is the complement (within `ℕ`) of the union of these forbidden sets. -/
def forbiddenSet (S : ResidueSystem) (i : ℕ) : Set ℕ :=
  {n | S.modulus i ≤ n ∧ n ≡ S.residue i [MOD S.modulus i]}

/-- Membership in `forbiddenSet S i` is exactly the negation of
`SatisfiesConstraint S i`. -/
theorem not_satisfiesConstraint_iff_mem_forbiddenSet
    {S : ResidueSystem} {i n : ℕ} :
    ¬ S.SatisfiesConstraint i n ↔ n ∈ S.forbiddenSet i := by
  unfold SatisfiesConstraint forbiddenSet
  constructor
  · intro h
    refine ⟨?_, ?_⟩
    · exact Nat.le_of_not_lt fun hlt => h (Or.inl hlt)
    · exact not_not.mp fun hne => h (Or.inr hne)
  · rintro ⟨h₁, h₂⟩ h
    rcases h with h | h
    · exact (Nat.lt_irrefl _ (lt_of_lt_of_le h h₁))
    · exact h h₂

/-- The avoided set is the complement of the union of all forbidden sets:
`A = ℕ \ ⋃ i, forbiddenSet S i`. This is the geometric reformulation of
Erdős problem `#25` as a sieve over a countable family of arithmetic
progressions. -/
theorem avoidedSet_eq_compl_iUnion_forbiddenSet (S : ResidueSystem) :
    S.avoidedSet = (⋃ i, S.forbiddenSet i)ᶜ := by
  ext n
  classical
  simp only [mem_avoidedSet_iff, Set.mem_compl_iff, Set.mem_iUnion, not_exists]
  constructor
  · intro hn i hni
    exact (not_satisfiesConstraint_iff_mem_forbiddenSet.mpr hni) (hn i)
  · intro hn i
    by_contra hsat
    exact hn i ((not_satisfiesConstraint_iff_mem_forbiddenSet.mp) hsat)

/-- Equivalent intersection form of the previous lemma: the avoided set is the
intersection of the complements of the forbidden sets. -/
theorem avoidedSet_eq_iInter_compl_forbiddenSet (S : ResidueSystem) :
    S.avoidedSet = ⋂ i, (S.forbiddenSet i)ᶜ := by
  rw [avoidedSet_eq_compl_iUnion_forbiddenSet]
  exact Set.compl_iUnion _

/-- Every forbidden set is contained in the corresponding shifted multiples
set, in the sense that every element of `forbiddenSet S i` is a multiple of
`modulus i` shifted by `residue i mod modulus i`. -/
theorem forbiddenSet_subset_multiples_shifted (S : ResidueSystem) (i : ℕ) :
    S.forbiddenSet i ⊆
      {n | ∃ k : ℕ, n = k * S.modulus i + (S.residue i % S.modulus i)} := by
  rintro n ⟨_h_ge, h_cong⟩
  -- `h_cong` says `n ≡ residue i [MOD modulus i]`, i.e.
  -- `n % modulus i = residue i % modulus i`.
  have h_mod : n % S.modulus i = S.residue i % S.modulus i := h_cong
  refine ⟨n / S.modulus i, ?_⟩
  conv_lhs => rw [← Nat.div_add_mod n (S.modulus i)]
  rw [h_mod, Nat.mul_comm]

/-- The single-modulus *multiples set* generated by `modulus i`: this is
`MultiplesOf (fun _ : Unit => S.modulus i)` in the language of
`Erdos.Common.ThickSequences`. We state it directly here as a convenience. -/
def modulusMultiples (S : ResidueSystem) (i : ℕ) : Set ℕ :=
  MultiplesOf (fun _ : Unit => S.modulus i)

/-- Unfolded characterization of `modulusMultiples`. -/
theorem mem_modulusMultiples_iff (S : ResidueSystem) (i n : ℕ) :
    n ∈ S.modulusMultiples i ↔ ∃ k : ℕ, n = k * S.modulus i := by
  unfold modulusMultiples MultiplesOf
  simp only [Set.mem_range, Prod.exists]
  constructor
  · rintro ⟨k, _, rfl⟩
    exact ⟨k, rfl⟩
  · rintro ⟨k, rfl⟩
    exact ⟨k, (), rfl⟩

/-- For the *purely periodic* case `residue i = 0`, the forbidden set is
exactly the positive multiples of `modulus i`. This is the cleanest bridge:
zero-residue avoidance is exactly multiple-avoidance, which is the object
of study in DeepMind's Erdős `#26` formalization. -/
theorem forbiddenSet_of_residue_zero (S : ResidueSystem) (i : ℕ)
    (h_res : S.residue i = 0) :
    S.forbiddenSet i =
      {n | S.modulus i ≤ n ∧ S.modulus i ∣ n} := by
  ext n
  unfold forbiddenSet
  classical
  simp only [Set.mem_setOf_eq, h_res, Nat.ModEq, Nat.zero_mod]
  constructor
  · rintro ⟨h_ge, h_mod⟩
    refine ⟨h_ge, ?_⟩
    rwa [Nat.dvd_iff_mod_eq_zero]
  · rintro ⟨h_ge, h_dvd⟩
    refine ⟨h_ge, ?_⟩
    rwa [← Nat.dvd_iff_mod_eq_zero]

/-! ### Finite-index avoidance is intersection of complements -/

/-- Avoidance on a finite index set is the intersection of the complements
of the finitely many forbidden sets. This is the *finite* sub-case of
Erdős problem `#25`, where the natural density is well-defined by the
inclusion–exclusion formula (developing that quantitative density formula
is out of scope for this file — we only record the structural identity). -/
theorem avoidedSetOn_finite_eq_iInter (S : ResidueSystem) (I : Finset ℕ) :
    S.avoidedSetOn (↑I : Set ℕ) = ⋂ i ∈ I, (S.forbiddenSet i)ᶜ := by
  ext n
  classical
  simp only [mem_avoidedSetOn_iff, AvoidsOn, Finset.mem_coe,
    Set.mem_iInter, Set.mem_compl_iff]
  constructor
  · intro hn i hi hmem
    exact (not_satisfiesConstraint_iff_mem_forbiddenSet.mpr hmem) (hn i hi)
  · intro hn i hi
    by_contra hsat
    exact hn i hi (not_satisfiesConstraint_iff_mem_forbiddenSet.mp hsat)

end ResidueSystem
end ResidueAvoidingDensity
