import Erdos.UlamPrimeRecurrence.Statement

/- 
# Elementary Facts About Ulam's Prime Recurrence

This file records the first concrete infrastructure for problem `#472`. We
prove uniqueness of the prescribed next prime, describe admissible values in a
finite prefix, and verify the example from the problem page:

`3, 5, 7, 11, 13, 17`.
-/
namespace UlamPrimeRecurrence

theorem mem_admissibleValues_iff {s : List ℕ} {x : ℕ} :
    x ∈ admissibleValues s ↔ ∃ q ∈ s, x = lastTerm s + q - 1 := by
  constructor
  · intro hx
    rcases Finset.mem_image.mp hx with ⟨q, hq, rfl⟩
    exact ⟨q, by simpa using hq, rfl⟩
  · rintro ⟨q, hq, rfl⟩
    exact Finset.mem_image.mpr ⟨q, by simpa using hq, rfl⟩

/-- The minimal admissible prime is unique whenever it exists. -/
theorem nextPrime_unique {s : List ℕ} {p q : ℕ}
    (hp : NextPrime s p) (hq : NextPrime s q) :
    p = q := by
  apply le_antisymm
  · exact hp.2.2.2 q hq.2.1 hq.2.2.1
  · exact hq.2.2.2 p hp.2.1 hp.2.2.1

/-- The seed `[3, 5]` is a legitimate starting seed of primes. -/
theorem threeFive_isPrimeSeed : PrimeSeed [3, 5] := by
  refine ⟨by decide, by simp, ?_⟩
  intro q hq
  have hq' : q = 3 ∨ q = 5 := by
    simpa using hq
  rcases hq' with rfl | rfl <;> norm_num

theorem admissibleValues_threeFive :
    admissibleValues [3, 5] = ({7, 9} : Finset ℕ) := by
  norm_num [admissibleValues, lastTerm]

theorem nextPrime_threeFive : NextPrime [3, 5] 7 := by
  refine ⟨by decide, ?_, by norm_num, ?_⟩
  · norm_num [admissibleValues, lastTerm]
  · intro r hr hprime
    have hr' : r = 7 ∨ r = 9 := by
      simpa [admissibleValues, lastTerm] using hr
    rcases hr' with rfl | rfl
    · omega
    · exfalso
      norm_num at hprime

theorem admissibleValues_threeFiveSeven :
    admissibleValues [3, 5, 7] = ({9, 11, 13} : Finset ℕ) := by
  norm_num [admissibleValues, lastTerm]

theorem nextPrime_threeFiveSeven : NextPrime [3, 5, 7] 11 := by
  refine ⟨by decide, ?_, by norm_num, ?_⟩
  · norm_num [admissibleValues, lastTerm]
  · intro r hr hprime
    have hr' : r = 9 ∨ r = 11 ∨ r = 13 := by
      simpa [admissibleValues, lastTerm] using hr
    rcases hr' with rfl | rfl | rfl
    · exfalso
      norm_num at hprime
    · omega
    · omega

theorem admissibleValues_threeFiveSevenEleven :
    admissibleValues [3, 5, 7, 11] = ({13, 15, 17, 21} : Finset ℕ) := by
  norm_num [admissibleValues, lastTerm]

theorem nextPrime_threeFiveSevenEleven : NextPrime [3, 5, 7, 11] 13 := by
  refine ⟨by decide, ?_, by norm_num, ?_⟩
  · norm_num [admissibleValues, lastTerm]
  · intro r hr hprime
    have hr' : r = 13 ∨ r = 15 ∨ r = 17 ∨ r = 21 := by
      simpa [admissibleValues, lastTerm] using hr
    rcases hr' with rfl | rfl | rfl | rfl
    · omega
    · exfalso
      norm_num at hprime
    · omega
    · exfalso
      norm_num at hprime

theorem admissibleValues_threeFiveSevenElevenThirteen :
    admissibleValues [3, 5, 7, 11, 13] = ({15, 17, 19, 23, 25} : Finset ℕ) := by
  norm_num [admissibleValues, lastTerm]

theorem nextPrime_threeFiveSevenElevenThirteen :
    NextPrime [3, 5, 7, 11, 13] 17 := by
  refine ⟨by decide, ?_, by norm_num, ?_⟩
  · norm_num [admissibleValues, lastTerm]
  · intro r hr hprime
    have hr' : r = 15 ∨ r = 17 ∨ r = 19 ∨ r = 23 ∨ r = 25 := by
      simpa [admissibleValues, lastTerm] using hr
    rcases hr' with rfl | rfl | rfl | rfl | rfl
    · exfalso
      norm_num at hprime
    · omega
    · omega
    · omega
    · exfalso
      norm_num at hprime

/-- The initial segment `3, 5, 7, 11, 13, 17` is generated by the Ulam-prime
recurrence starting from the seed `[3, 5]`. -/
theorem threeFive_prefix_3_5_7_11_13_17 :
    UlamPrimePrefixes [3, 5] [3, 5, 7, 11, 13, 17] := by
  have h0 : UlamPrimePrefixes [3, 5] [3, 5] :=
    UlamPrimePrefixes.base threeFive_isPrimeSeed
  have h1 : UlamPrimePrefixes [3, 5] [3, 5, 7] := by
    simpa using UlamPrimePrefixes.step h0 nextPrime_threeFive
  have h2 : UlamPrimePrefixes [3, 5] [3, 5, 7, 11] := by
    simpa using UlamPrimePrefixes.step h1 nextPrime_threeFiveSeven
  have h3 : UlamPrimePrefixes [3, 5] [3, 5, 7, 11, 13] := by
    simpa using UlamPrimePrefixes.step h2 nextPrime_threeFiveSevenEleven
  have h4 : UlamPrimePrefixes [3, 5] [3, 5, 7, 11, 13, 17] := by
    simpa using UlamPrimePrefixes.step h3 nextPrime_threeFiveSevenElevenThirteen
  exact h4

/-- In particular, the seed `[3, 5]` already yields a valid prefix of length
`6`. -/
theorem exists_threeFive_prefix_length_six :
    ∃ s : List ℕ, UlamPrimePrefixes [3, 5] s ∧ 6 ≤ s.length := by
  refine ⟨[3, 5, 7, 11, 13, 17], threeFive_prefix_3_5_7_11_13_17, ?_⟩
  norm_num

end UlamPrimeRecurrence
