#!/usr/bin/env python3
"""Aggregate par_target/*.txt results into a multiplicity table.

Columns expected in each line:
   N <tab> |A| <tab> n* <tab> r <tab> 2r-|A| <tab> a1,a2,...
"""
from __future__ import annotations
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
PAR_DIR = os.path.join(HERE, "par_target")
OUT_DIR = os.path.dirname(HERE)  # research/sqrt2-strong-almost-sidon


def parse_file(path):
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path) as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            bits = line.split("\t")
            if len(bits) != 6:
                continue
            try:
                N = int(bits[0]); sz = int(bits[1]); ns = int(bits[2])
                r = int(bits[3]); inv = int(bits[4])
                A = [int(x) for x in bits[5].split(",")]
            except ValueError:
                continue
            rows.append({"N": N, "size": sz, "n_star": ns, "r": r,
                         "inv": inv, "A": A})
    return rows


def main():
    all_rows = []
    if os.path.isdir(PAR_DIR):
        for fn in sorted(os.listdir(PAR_DIR)):
            if not fn.endswith(".txt"):
                continue
            all_rows.extend(parse_file(os.path.join(PAR_DIR, fn)))

    # Group by N -> max size found, and aggregate.
    by_N = defaultdict(list)
    for r in all_rows:
        by_N[r["N"]].append(r)

    # Per-N best size:
    print(f"# Aggregated multiplicity invariant data")
    print(f"# columns: N <tab> max_size_found <tab> count <tab> "
          f"r_min <tab> r_max <tab> inv_min <tab> inv_max <tab> anomalies")
    anomalies = []
    table_lines = []
    for N in sorted(by_N):
        rows = by_N[N]
        max_size = max(r["size"] for r in rows)
        top = [r for r in rows if r["size"] == max_size]
        rs = [r["r"] for r in top]
        invs = [r["inv"] for r in top]
        anom = [r for r in top if r["inv"] >= 2]
        if anom:
            anomalies.extend(anom)
        line = (f"{N}\t{max_size}\t{len(top)}\t"
                f"{min(rs)}\t{max(rs)}\t{min(invs)}\t{max(invs)}\t{len(anom)}")
        print(line)
        table_lines.append(line)

    # Write multiplicity table file.
    out_path = os.path.join(HERE, "multiplicity-table.txt")
    with open(out_path, "w") as f:
        f.write("# Multiplicity invariant table for SAS extremizers\n")
        f.write("# Generated by aggregate_multiplicity.py\n")
        f.write("# Columns: N <tab> max_size_found <tab> n_extremizers <tab> "
                "r_min <tab> r_max <tab> inv_min <tab> inv_max <tab> n_anomalies\n")
        f.write("# (inv = 2*r_A(n*) - |A|; the empirical invariant is inv ∈ {0,1})\n")
        f.write("\n")
        for line in table_lines:
            f.write(line + "\n")
        if anomalies:
            f.write("\n# ANOMALIES (inv >= 2):\n")
            for a in anomalies:
                f.write(f"#   N={a['N']} size={a['size']} n*={a['n_star']} "
                        f"r={a['r']} inv={a['inv']}\n")
                f.write(f"#     A = {a['A']}\n")
        else:
            f.write("\n# No anomalies found (all observed extremizers have inv ∈ {0, 1})\n")
    print(f"\nWrote {out_path}")

    if anomalies:
        print(f"\n*** {len(anomalies)} ANOMALIES FOUND ***")
    else:
        print("\nNo invariant violations.")


if __name__ == "__main__":
    main()
